name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout site repo
      uses: actions/checkout@v3

    - name: Checkout private images repo
      uses: actions/checkout@v3
      with:
        repository: jarla-t/jarla-images
        token: ${{ secrets.PRIVATE_IMAGES_TOKEN }}
        path: images-temp

    - name: Copy images into site
      run: |
        mkdir -p assets/images
        cp -r images-temp/* assets/images/

    - name: Debug – list private repo contents before copy
      run: |
        echo "Contents of images-temp:"
        ls -R images-temp || echo "No files found in images-temp"

    - name: Debug – list images after copy
      run: |
        echo "Contents of assets/images after copy:"
        ls -R assets/images || echo "No files found in assets/images"

    - name: Debug – check exact file names
      run: |
        echo "Listing with file sizes to check case and extension:"
        find assets/images -type f -exec ls -lh {} \;

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

