title: "Your Name"
email: "your.email@example.com"
description: "A minimal mistakes based academic + hobby website"
baseurl: ""
url: "https://jarla-t.github.io"
repository: "https://github.com/jarla-t/jarla-t.github.io"
theme: jekyll-theme-cayman

navigation:
  - title: "Research"
    url: /research/
  - title: "CV"
    url: /cv/
  - title: "Publications"
    url: /publications/
  - title: "Hobbies"
    url: /hobbies/
  - title: "Photography"
    url: /photography/
