title: "Jarla Thiesbrummel"
email: "your.email@example.com"
description: "A minimal mistakes based academic + hobby website"
baseurl: ""
url: "https://jarla-t.github.io"
#repository: "https://github.com/jarla-t/jarla-t.github.io"
repository: "jarla-t/jarla-t.github.io"

# Use the remote_theme plugin to load Minimal Mistakes from GitHub
remote_theme: mmistakes/minimal-mistakes@3.4.8


plugins:
  - jekyll-remote-theme
  - jekyll-feed

navigation:
  - title: "Research"
    url: /research/
  - title: "CV"
    url: /cv/
  - title: "Publications"
    url: /publications/
  - title: "Hobbies"
    url: /hobbies/
  - title: "Photography"
    url: /photography/

footer:
  nav: "footer"

