name: Debug Private Images

on:
  workflow_dispatch:

jobs:
  debug-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo (main site)
        uses: actions/checkout@v3

      - name: Test token access
        run: |
          echo "Testing token access..."
          curl -i -H "Authorization: token ${{ secrets.NEW_IMAGE_TOKEN }}" \
               https://api.github.com/repos/jarla-t/jarla-images || echo "Token test failed"

      - name: Test git ls-remote
        run: |
          echo "Testing git access..."
          git ls-remote https://x-access-token:${{ secrets.NEW_IMAGE_TOKEN }}@github.com/jarla-t/jarla-images.git || echo "git ls-remote failed"

      - name: Clone private repo
        run: |
          echo "Trying manual clone..."
          git clone https://x-access-token:${{ secrets.NEW_IMAGE_TOKEN }}@github.com/jarla-t/jarla-images.git images-temp || echo "git clone failed"
          ls -R images-temp || echo "No files found"
