name: Debug Private Images

on:
  workflow_dispatch:  # allows you to trigger manually

jobs:
  debug-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main site repo
        uses: actions/checkout@v3

      - name: Debug – manual git clone of private images
        run: |
          echo "Trying to clone private repo..."
          git clone https://${{ secrets.NEW_IMAGE_TOKEN }}@github.com/jarla-t/jarla-images.git images-temp
          echo "Listing contents of images-temp:"
          ls -R images-temp || echo "No files found"

        cd images-temp
        git branch
        git remote -v
