name: Debug Private Images

on:
  workflow_dispatch:

jobs:
  debug-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main site repo
        uses: actions/checkout@v3

      - name: Clone private images repo manually
        run: |
          echo "Cloning private repo..."
          git clone https://x-access-token:${{ secrets.NEW_IMAGE_TOKEN }}@github.com/jarla-t/jarla-images.git images-temp
          cd images-temp
          echo "Switching to main branch explicitly..."
          git fetch origin main
          git checkout main
          echo "Listing contents of images-temp:"
          ls -R
