name: Build Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout website repo
        uses: actions/checkout@v3

      - name: Checkout images repo
        uses: actions/checkout@v3
        with:
          repository: jarla-t/jarla-images
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: images-temp
          ref: main               # explicitly specify the branch
          ssh-strict: true
          persist-credentials: false
          clean: true
          fetch-depth: 1
          fetch-tags: false
          lfs: false
          submodules: false
          set-safe-directory: true

      # Add your next build steps here, e.g., build the site, move images, etc.
