name: Debug Private Images

on:
  workflow_dispatch:  # allows manual triggering

jobs:
  debug-images:
    runs-on: ubuntu-latest
    steps:
      # Checkout the main site repo (current repository)
      - name: Checkout main site repo
        uses: actions/checkout@v3

      # Checkout the private images repo
      - name: Checkout private images repo
        uses: actions/checkout@v3
        with:
          repository: jarla-t/jarla-images
          token: ${{ secrets.NEW_IMAGE_TOKEN }}
          path: images-temp  # clones into this folder

      # Debug – list contents and git info
      - name: Debug – verify private repo
        run: |
          echo "Listing contents of images-temp:"
          ls -R images-temp || echo "No files found"

          echo "Current branch:"
          cd images-temp
          git branch

          echo "Remotes:"
          git remote -v
