name: Debug Private Images

on:
  workflow_dispatch:

jobs:
  debug-images:
    runs-on: ubuntu-latest
    steps:
      - name: Debug – show GitHub Actions env
        run: |
          echo "HOME=$HOME"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_TOKEN secret exists? ${NEW_IMAGE_TOKEN:+yes}"

      - name: Debug – manual clone with token
        run: |
          echo "Trying to clone private repo..."
          git --version
          git clone https://${{ secrets.NEW_IMAGE_TOKEN }}@github.com/jarla-t/jarla-images.git images-temp || echo "Clone failed"
          echo "Listing contents of images-temp (if any):"
          ls -R images-temp || echo "No files found"

      - name: Debug – inspect cloned repo
        if: success()
        run: |
          cd images-temp
          echo "Branches:"
          git branch -a
          echo "Remotes:"
          git remote -v
